name: CreateFlatpak

on:
  pull_request:
    paths:
      - 'org.gramps_project.Gramps.Plugin.WebSearch.yml'
  workflow_dispatch:

jobs:
  flatpak:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: InstallFlatpak
      run: |
        sudo add-apt-repository ppa:flatpak/stable
        sudo apt update
        sudo apt install flatpak flatpak-builder python3-pip

    - name: SetupFlatpak
      run: |
        flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install flathub org.gnome.Platform//49 org.gnome.Sdk//49 -y
        
    - name: DownloadGramps
      run: |
        curl -L -o gramps.flatpak https://github.com/OzarkShepherd/flatpak/releases/download/plugintest/gramps.flatpak

    - name: InstallGramps
      run: |
        flatpak install --user -y gramps.flatpak

    - name: BuildFlatpak
      run: |
        flatpak-builder --repo=repo --force-clean build-dir org.gramps_project.Gramps.Plugin.WebSearch.yml

    - name: BuildBundle
      run: |
        flatpak build-bundle repo gramps.WebSearch.flatpak org.gramps_project.Gramps.Plugin.WebSearch.yml

    - name: UploadBundle
      uses: actions/upload-artifact@main
      with:
        name: gramps.WebSearch.flatpak
        path: gramps.WebSearch.flatpak
